[package]
name = "legumemanager"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0"
users = "0.11.0"
clap = { version = "4.0", features = ["derive"] }
reqwest = { version = "0.11.24", features = ["blocking"]}

